// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Audit struct {
	CreatedAt   time.Time  `json:"createdAt"`
	CreatedBy   *string    `json:"createdBy,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	UpdatedBy   *string    `json:"updatedBy,omitempty"`
	PublishedAt *time.Time `json:"publishedAt,omitempty"`
	PublishedBy *string    `json:"publishedBy,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
